version: '3'
services: 
  fastapi:
    build: fastapi/
    ports:
      - '8000:8000'
    container_name: fastapi
    networks: 
      - tweet_network
  streamlit:
    build: streamlit/
    ports:
      - '8502:8502'
    container_name: streamlit
    networks: 
      - tweet_network

networks: 
  tweet_network:
    driver: bridge